{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-native-secrets.fullname" . }}
  labels:
    {{- include "kubernetes-native-secrets.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-native-secrets.fullname" . }}
  labels:
    {{- include "kubernetes-native-secrets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-native-secrets.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-native-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
