{{- if .Values.config.createSecretsNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.config.secretsNamespace }}
  labels:
    {{- include "kubernetes-native-secrets.labels" . | nindent 4 }}
{{- end }}
