{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-native-secrets.fullname" . }}
  labels:
    {{- include "kubernetes-native-secrets.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.dex.clientSecretKey }}: {{ .Values.secrets.dexClientSecret | quote }}
  {{ .Values.config.nextAuth.secretKey }}: {{ .Values.secrets.nextAuthSecret | quote }}
{{- end }}
